var:
  isu1:
    tasks:
      - isu/delve.yml
    other:
      - other/alp.yml
      # - other/collect.yml
      - other/graphviz.yml
      - other/mysql.yml
      - other/netdata.yml
      - other/nginx.yml
      - other/parameter.yml
      - other/percona.yml
