- name: remove
  file:
    path: "{{ home_dir }}/webapp"
    state: absent

- name: Git checkout
  git:
    repo: "https://github.com/{{ git_user }}/{{ git_repo }}.git"
    dest: "{{ home_dir }}/{{ git_repo }}"

- name: Copy
  copy:
    src: "{{ home_dir }}/{{ git_repo }}/webapp"
    dest: "{{ home_dir }}/"
    owner: isucon
    group: isucon
    remote_src: yes
  ignore_errors: yes

- name: remove
  file:
    path: "{{ home_dir }}/{{ git_repo }}"
    state: absent

- name: isupipe-go is restarted
  systemd:
    name: isupipe-go
    state: restarted
# - name: remove
#   file:
#     path: /var/log/nginx/access.log
#     state: absent

# - name: nginx is restarted
#   systemd:
#     name: nginx
#     state: restarted

# - name: remove
#   file:
#     path: /var/log/mysql/mysql-slow.sql
#     state: absent

# - name: mysql is restarted
#   systemd:
#     name: mysql
#     state: restarted
