- name: remove
  file:
    path: "{{ home_dir }}/webapp"
    state: absent

- name: Git checkout
  git:
    repo: "https://github.com/{{ git_user }}/{{ git_repo }}.git"
    dest: "{{ home_dir }}/{{ git_repo }}"

- name: Copy
  copy:
    src: "{{ home_dir }}/{{ git_repo }}/webapp"
    dest: "{{ home_dir }}/"
    owner: isucon
    group: isucon
    remote_src: yes
  ignore_errors: yes

- name: remove
  file:
    path: "{{ home_dir }}/{{ git_repo }}"
    state: absent

- name: shell
  shell: mysql -u isucon -pisucon -e "DROP DATABASE IF EXISTS isupipe"
  ignore_errors: yes

- name: shell
  shell: mysql -u isucon -pisucon -e "CREATE DATABASE IF NOT EXISTS isupipe"
  ignore_errors: yes

- name: shell
  shell: cat "{{ home_dir }}/webapp/sql/initdb.d/10_schema.sql" | sudo mysql isupipe
  ignore_errors: yes

- name: shell
  shell: "bash {{ home_dir }}/webapp/sql/init.sh"
  ignore_errors: yes

- name: shell
  shell: sudo -u isucon bash -lc "make"
  args:
    chdir: "{{ home_dir }}/webapp/go/"

- name: service
  service:
    name: isupipe-go
    state: restarted

- name: file
  file:
    path: /var/log/nginx/access.log
    state: absent

- name: service
  service:
    name: nginx
    state: restarted

- name: file
  file:
    path: /var/log/mysql/mysql-slow.sql
    state: absent

- name: service
  service:
    name: mysql
    state: restarted
