- name: copy
  ansible.builtin.copy:
    src: /home/ubuntu/.ssh/authorized_keys
    dest: /home/isucon/.ssh/authorized_keys
    owner: isucon
    group: isucon
    mode: "0600"
    remote_src: true

- name: hostname
  ansible.builtin.hostname:
    name: isu1

- name: lineinfile
  lineinfile:
    dest: /etc/hosts
    insertafter: EOF
    line: "{{ item }}"
  with_items:
    - "10.1.1.11 isu-1"

- name: shell
  shell: |
    cd /etc/nginx/tls/ && \
    openssl req -subj '/CN=*.t.isucon.local' -nodes -newkey rsa:2048 -keyout _.u.isucon.local.key -out _.u.isucon.local.csr && \
    echo "subjectAltName=DNS.1:*.u.isucon.local, DNS.2:*.u.isucon.dev" > extfile.txt && \
    openssl x509 -in _.u.isucon.local.csr -req -signkey _.u.isucon.local.key -sha256 -days 3650 -out _.u.isucon.local.crt -extfile extfile.txt && \
    cp -p _.u.isucon.local.crt _.u.isucon.local.issuer.crt
  register: result
  changed_when: false
- name: show stdout
  debug:
    msg: "{{ result.stdout_lines }}"

- name: service
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: shell
  shell: pdnsutil delete-zone u.isucon.local && pdnsutil delete-zone u.isucon.dev
  register: result
  changed_when: false
  ignore_errors: true
- name: show stdout
  debug:
    msg: "{{ result.stdout_lines }}"

- name: file
  file:
    path: /opt/aws-env-isucon-subdomain-address.sh.lock
    state: absent

- name: Reboot the machine (Wait for 5 min)
  reboot:
    reboot_timeout: 300

- name: file
  ansible.builtin.file:
    path: /etc/powerdns/pdns.conf
    mode: "0644"

- name: Copy
  copy:
    src: ../../files/nginx/sites-enabled/init-isupipe.conf
    dest: /etc/nginx/sites-enabled/isupipe.conf
    mode: "0644"

- name: reloaded
  systemd:
    name: nginx
    state: reloaded
