name: "isu bench"
on:
  workflow_dispatch:
jobs:
  Ansible1:
    name: "Ansible1 Job"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/isu_bm.yml
          directory: ./ansible
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [isu-bm]
            ${{ vars.HOST_BM }}
          options: |
            -i .hosts
            -e "target_ip=${{ vars.HOST1 }}"
